In [4]:
from Process import PlateReader
import pandas as pd

# Step 1: Load Sample Information
* Ideally will be in the form of a dataframe. This dataframe should be standardized in the original documentation where we originally made the sample. 
* Either load locally or pull from the google team drive (still working on fixing pulling from Drive)

In [5]:
sample_info = pd.read_csv(r"C:\Users\Edwin\Downloads\Experiment Synthesis Info")

# Step 2: Load UV-Vis Data
* ***If loading from plate reader***: Once the plate has been read, allow for exporting to an excel sheet and reformat for easy upload and merging.
    * The plate reader should automatically ask you if you would like to export to excel. When running multiple plates you can just keep selecting export and it will automatically add the new run as an additional sheet to the originally generated excel sheet. 
    * To format for easy loading:
        1. Create a new sheet in the same exported excel file and name it something simple (i.e. sheet1). 
        2. Copy the data from the sheet and add it to the newly created sheet. Make sure to paste in the data as "only values". 
        3. Repeat for every single exported sheet (i.e. every plate)
        
        
* Sometimes when using the plate reader the scanning protocol scans the whole plate versus only the wells of interest. This can be changed, however it is common to forget. If you do forget to do this, make sure to trim the dataframe to match the same length/order of wells as the sample info loaded in Step 1.


* ***If loading from single cuvette reader***: 
    * Still documenting.

***Step 2a:*** Provide the path of the excel sheet for the plate reader. With this you will also need to provide the **Sheet Name** of for correct excel sheet to be extracted. Since multiple plates are expected to be used at once, provide the Sheet names as a ***list of string names***. This will return a list of dataframes of each plate in the order the sheet names provided.

*Hmm maybe make dataframes as dictionary so you can look and debug later*

In [6]:
path = r"C:\Users\Edwin\Downloads\03_03_21_Left_Robot.xlsx"
plate_names = ['Sheet1','Sheet2','Sheet3']
plate_dfs = PlateReader.extract_plates(path, plate_names)

***Step 2b:*** With the dataframes from ***Step2a***, given that all the plates read originally were done using the same protcol, then we can merge these dataframes into one. The only thing we need to edit is when originally formatting the excel sheets, since we copied the wavelength row in each sheet it only needs to be present once. A way to avoid to this is to copy it only in the first plate sheet you are using.

In [7]:
merged_df = PlateReader.merge_wavelength_dfs(plate_dfs)

# Trim if needed
merged_df = merged_df[:len(sample_info)]

***Step 2c:*** Sometimes when samples are extremely turbid or have some sort of material like foam or cream the plate reader absorbance is overflowed and returns as 'OVRFLW'. This will prevent you from handling the entire set of data, so what can be done is replace the 'OVRFLW' values with a holder number. It is reccomended you select a very high holder number so you can track and isolate it easier if needed.

In [8]:
merged_df = PlateReader.detect_ovflw(merged_df, holder = 30)
# merged_df.drop(['Wavelength'], inplace = True)
merged_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
Wavelength,200,250,300,350,400,450,500,550,600,650,700,750,800,850,900
A1,3.48,3.738,0.778,0.328,0.056,0.048,0.045,0.045,0.045,0.043,0.043,0.044,0.044,0.044,0.054
A2,3.492,3.734,0.809,0.352,0.078,0.062,0.053,0.049,0.047,0.045,0.044,0.055,0.052,0.061,0.095
A3,3.477,3.72,0.719,0.312,0.079,0.066,0.056,0.053,0.051,0.048,0.047,0.056,0.054,0.061,0.098
A4,3.46,3.715,0.661,0.276,0.063,0.052,0.047,0.045,0.043,0.041,0.041,0.049,0.048,0.054,0.095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C7,3.449,3.712,0.602,0.241,0.048,0.042,0.037,0.036,0.036,0.035,0.034,0.036,0.035,0.037,0.04
C8,3.459,3.698,0.641,0.259,0.049,0.04,0.037,0.037,0.038,0.037,0.038,0.049,0.047,0.055,0.09
D1,3.474,3.726,0.707,0.29,0.051,0.042,0.041,0.041,0.04,0.038,0.037,0.046,0.045,0.051,0.089
D2,3.462,3.699,0.628,0.256,0.05,0.041,0.041,0.038,0.04,0.04,0.039,0.046,0.044,0.049,0.091
D3,3.456,3.711,0.621,0.251,0.049,0.043,0.038,0.038,0.04,0.038,0.037,0.043,0.044,0.049,0.093

# Step 3: Merge with Sample Info Dataframe

The first step to merge to sample info dataframe is to format the plate reader dataframe to have the wavelengths as the column names versus as an another row. We can do this by isolating the Wavelength row, adding the appropiate unit the string of each element of the wavlength row and reassigning this new list as the column names. We finalize this by dropping the wavlength row.

In [9]:
platereader_df = PlateReader.merge_sampleinfo_platereader(sample_info, merged_df)

Next we reset both indexes of the two dataframes we are to merge and concatnate them together. We drop and reset indexes to ensure any past dependency is forgotten, so you must make sure your sample info dataframe and plate reader dataframe are ordered correctly where row 1...n of one dataframe referes to row 1...n of the other.

In [10]:
sample_info.reset_index(drop=True, inplace=True)
platereader_df.reset_index(drop=True, inplace=True)
combined_df = pd.concat([sample_info, platereader_df], axis = 1)
combined_df

,UID,dppc wtf,dspepeg200 wtf,pfh wtf,ethanol wtf,water wtf,Well,Labware,Slot,200nm,...,450nm,500nm,550nm,600nm,650nm,700nm,750nm,800nm,850nm,900nm
0,S2_A1_05-03-2021_Right,0.0001,0.000035,0.0,0.222222,0.777643,A1,Falcon 48 Well Plate 1500 ÂµL,2,3.48,...,0.048,0.045,0.045,0.045,0.043,0.043,0.044,0.044,0.044,0.054
1,S2_A2_05-03-2021_Right,0.0001,0.000035,0.0,0.333333,0.666532,A2,Falcon 48 Well Plate 1500 ÂµL,2,3.492,...,0.062,0.053,0.049,0.047,0.045,0.044,0.055,0.052,0.061,0.095
2,S2_A3_05-03-2021_Right,0.0001,0.000035,0.0,0.444444,0.555421,A3,Falcon 48 Well Plate 1500 ÂµL,2,3.477,...,0.066,0.056,0.053,0.051,0.048,0.047,0.056,0.054,0.061,0.098
3,S2_A4_05-03-2021_Right,0.0001,0.000035,0.0,0.555556,0.444309,A4,Falcon 48 Well Plate 1500 ÂµL,2,3.46,...,0.052,0.047,0.045,0.043,0.041,0.041,0.049,0.048,0.054,0.095
4,S2_A5_05-03-2021_Right,0.0001,0.000035,0.0,0.666667,0.333198,A5,Falcon 48 Well Plate 1500 ÂµL,2,3.459,...,0.046,0.042,0.044,0.043,0.04,0.039,0.048,0.048,0.054,0.097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,S5_C8_05-03-2021_Right,0.0000,0.000000,0.0,0.445579,0.554421,C8,Falcon 48 Well Plate 1500 ÂµL,5,3.459,...,0.04,0.037,0.037,0.038,0.037,0.038,0.049,0.047,0.055,0.09
120,S5_D1_05-03-2021_Right,0.0000,0.000000,0.0,0.556691,0.443309,D1,Falcon 48 Well Plate 1500 ÂµL,5,3.474,...,0.042,0.041,0.041,0.04,0.038,0.037,0.046,0.045,0.051,0.089
121,S5_D2_05-03-2021_Right,0.0000,0.000000,0.0,0.667802,0.332198,D2,Falcon 48 Well Plate 1500 ÂµL,5,3.462,...,0.041,0.041,0.038,0.04,0.04,0.039,0.046,0.044,0.049,0.091
122,S5_D3_05-03-2021_Right,0.0000,0.000000,0.0,0.778913,0.221087,D3,Falcon 48 Well Plate 1500 ÂµL,5,3.456,...,0.043,0.038,0.038,0.04,0.038,0.037,0.043,0.044,0.049,0.093
123,S5_D4_05-03-2021_Right,0.0000,0.000000,0.0,0.890024,0.109976,D4,Falcon 48 Well Plate 1500 ÂµL,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Step 4: Format Dataframe as csv and Upload to Drive.
We simply call a method of the dataframe while ensuring to drop the index (again to remove and previous dependency). 

***If uploading from desktop***: Just grab and upload like any other file.

***If uploading from jupyter notebook***: Save the csv anywhere with a name that is not relevant, reccomended is something like "Temp File" as you will be uploading it to google drive under a different name. Then use the Gdrive module of functions from the Prepare package. Read the README in this package to understand how to use it, it will require a certain setup of credentials.

In [14]:
temp_hold_path = r"Temp file"
combined_df_csv = combined_df.to_csv(temp_hold_path, index=False)

In [16]:
from Prepare import CreateSamples

In [17]:
CreateSamples.team_drive_dict()

AttributeError: module 'Prepare.CreateSamples' has no attribute 'team_drive_dict'

In [ ]:
current_members = CreateSamples.file_and_folder_navi('1dXYmxuESNhgmVHntEf8hnZmjK0Br8b64')
CreateSamples.file_and_folder_navi('1CDnoLE32bG0BFhhvCl5JlRFO4I_ga-eJ')

In [ ]:
file_to_upload = temp_hold_path 
folder_to_place_id = '1YXrIIXT3uSFd5-NSpht-1wB1-7hH6Y1w'
name_upload = 'Synthesis and UVVis'

CreateSamples.upload_to_team_drive_folder(folder_to_place_id, file_to_upload, name_upload)