In [1]:
from Process import PlateReader
import pandas as pd

### Step 1: Load Sample Information
* Ideally will be in the form of a dataframe. This dataframe should be standardized in the original documentation where we originally made the sample. 
* Either load locally or pull from the google team drive (still working on fixing pulling from Drive)

In [10]:
sample_info = pd.DataFrame(data=[0, 5,10,40], columns = ['Sonication Time']) #pd.read_csv(r"04_16_21_Yt")
sample_info['84mM Cd:TOP volf'] = [0, 0.75, 0.75, 0.75]
sample_info['1M Se:TOP volf'] = [0, 0.25, 0.25, 0.25]
sample_info['Ocatdecence volf'] = [100, 0, 0, 0]

   Sonication Time  84mM Cd:TOP volf  1M Se:TOP volf  Ocatdecence volf
0                0              0.00            0.00               100
1                5              0.75            0.25                 0
2               10              0.75            0.25                 0
3               40              0.75            0.25                 0

### Step 2: Load UV-Vis Data
* ***If loading from plate reader***: Once the plate has been read, allow for exporting to an excel sheet and reformat for easy upload and merging.
    * The plate reader should automatically ask you if you would like to export to excel. When running multiple plates you can just keep selecting export and it will automatically add the new run as an additional sheet to the originally generated excel sheet. 
    * To format for easy loading:
        1. Create a new sheet in the same exported excel file and name it something simple (i.e. sheet1). 
        2. Copy the data from the sheet and add it to the newly created sheet. Make sure to paste in the data as "only values". 
        3. Repeat for every single exported sheet (i.e. every plate)
         
* Sometimes when using the plate reader the scanning protocol scans the whole plate versus only the wells of interest. This can be changed, however it is common to forget. If you do forget to do this, make sure to trim the dataframe to match the same length/order of wells as the sample info loaded in Step 1.

* ***If loading from single cuvette reader***: 
    * Still documenting.

***Step 2a:*** Provide the path of the excel sheet for the plate reader. With this you will also need to provide the **Sheet Name** of for correct excel sheet to be extracted. Since multiple plates are expected to be used at once, provide the Sheet names as a ***list of string names***. This will return a list of dataframes of each plate in the order the sheet names provided.

In [32]:
path = r"C:\Users\Edwin\Desktop\05_04_21_FL.xlsx"
plate_names = ['85', '95']
plate_dfs = PlateReader.extract_plates(path, plate_names)

***Step 2b:*** With the dataframes from ***Step2a***, given that all the plates read originally were done using the same protcol, then we can merge these dataframes into one. The only thing we need to edit is when originally formatting the excel sheets, since we copied the wavelength row in each sheet it only needs to be present once. A way to avoid to this is to copy it only in the first plate sheet you are using. 

Should be length of sample_info + 1 (will remove the wavelength column shortly).

In [33]:
merged_df = PlateReader.merge_wavelength_dfs(plate_dfs)
merged_df

KeyError: "['Wavelength'] not found in axis"

***Step 2c:*** Sometimes when samples are extremely turbid or have some sort of material like foam or cream the plate reader absorbance is overflowed and returns as 'OVRFLW'. This will prevent you from handling the entire set of data, so what can be done is replace the 'OVRFLW' values with a holder number. It is reccomended you select a very high holder number so you can track and isolate it easier if needed.

In [17]:
merged_df = PlateReader.detect_ovflw(merged_df, holder = 30)
merged_df

,0,1,2,3,4,5,6,7,8,9,...,391,392,393,394,395,396,397,398,399,400
Wavelength,300.000,301.000,302.000,303.000,304.000,305.000,306.000,307.000,308.000,309.000,...,691.000,692.000,693.000,694.000,695.000,696.000,697.000,698.000,699.000,700.000
B1,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
B2,1.085,1.019,0.973,0.920,0.872,0.825,0.788,0.752,0.719,0.690,...,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001
B3,2.602,2.514,2.430,2.342,2.248,2.172,2.104,2.028,1.966,1.914,...,0.042,0.042,0.042,0.042,0.042,0.041,0.041,0.041,0.041,0.041
B4,3.371,3.366,3.363,3.356,3.370,3.370,3.363,3.366,3.369,3.369,...,0.245,0.244,0.243,0.242,0.241,0.240,0.239,0.238,0.237,0.237

# Step 3: Merge with Sample Info Dataframe

The first step to merge to sample info dataframe is to format the plate reader dataframe to have the wavelengths as the column names versus as an another row. We can do this by isolating the Wavelength row, adding the appropiate unit the string of each element of the wavlength row and reassigning this new list as the column names. We finalize this by dropping the wavlength row.

In [18]:
platereader_df = PlateReader.rehead_wavelengths(merged_df)
platereader_df

,300.0nm,301.0nm,302.0nm,303.0nm,304.0nm,305.0nm,306.0nm,307.0nm,308.0nm,309.0nm,...,691.0nm,692.0nm,693.0nm,694.0nm,695.0nm,696.0nm,697.0nm,698.0nm,699.0nm,700.0nm
B1,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
B2,1.085,1.019,0.973,0.920,0.872,0.825,0.788,0.752,0.719,0.690,...,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001
B3,2.602,2.514,2.430,2.342,2.248,2.172,2.104,2.028,1.966,1.914,...,0.042,0.042,0.042,0.042,0.042,0.041,0.041,0.041,0.041,0.041
B4,3.371,3.366,3.363,3.356,3.370,3.370,3.363,3.366,3.369,3.369,...,0.245,0.244,0.243,0.242,0.241,0.240,0.239,0.238,0.237,0.237

Next we reset both indexes of the two dataframes we are to merge and concatnate them together. We drop and reset indexes to ensure any past dependency is forgotten, so you must make sure your sample info dataframe and plate reader dataframe are ordered correctly where row 1...n of one dataframe referes to row 1...n of the other.

In [21]:
sample_info.reset_index(drop=True, inplace=True)
platereader_df.reset_index(drop=True, inplace=True)
combined_df = pd.concat([sample_info, platereader_df], axis = 1) # this is called combine hotdog. 
combined_df

,Sonication Time,84mM Cd:TOP volf,1M Se:TOP volf,Ocatdecence volf,300.0nm,301.0nm,302.0nm,303.0nm,304.0nm,305.0nm,...,691.0nm,692.0nm,693.0nm,694.0nm,695.0nm,696.0nm,697.0nm,698.0nm,699.0nm,700.0nm
0,0,0.00,0.00,100,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1,5,0.75,0.25,0,1.085,1.019,0.973,0.920,0.872,0.825,...,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001
2,10,0.75,0.25,0,2.602,2.514,2.430,2.342,2.248,2.172,...,0.042,0.042,0.042,0.042,0.042,0.041,0.041,0.041,0.041,0.041
3,40,0.75,0.25,0,3.371,3.366,3.363,3.356,3.370,3.370,...,0.245,0.244,0.243,0.242,0.241,0.240,0.239,0.238,0.237,0.237

# Step 4: Format Dataframe as csv and Upload to Drive.
We simply call a method of the dataframe while ensuring to drop the index (again to remove and previous dependency). 

***If uploading from desktop***: Just grab and upload like any other file.

***If uploading from jupyter notebook***: Save the csv anywhere with a name that is not relevant, reccomended is something like "Temp File" as you will be uploading it to google drive under a different name. Then use the Gdrive module of functions from the Prepare package. Read the README in this package to understand how to use it, it will require a certain setup of credentials.

In [22]:
temp_hold_path = r"05_03_21_CdTOP_Blanked_Abs"
combined_df_csv = combined_df.to_csv(temp_hold_path, index=False)

,Total Volume,CdOl 84mM volpct,TOP 1mM volpct,ZnOl 84mM volpct,Time Sonicated,200nm,205nm,210nm,215nm,220nm,...,855nm,860nm,865nm,870nm,875nm,880nm,885nm,890nm,895nm,900nm
0,5.0,75.0,25.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1,5.0,75.0,25.0,0.0,0.0,-0.007,-0.015,-0.007,-0.007,-0.006,...,-0.006,-0.006,-0.006,-0.006,-0.005,-0.006,-0.005,-0.005,-0.005,-0.005
2,5.0,75.0,24.5,0.5,0.0,0.047,0.042,0.052,0.051,0.045,...,-0.007,-0.007,-0.007,-0.007,-0.006,-0.006,-0.006,-0.005,-0.005,-0.005
3,5.0,75.0,24.5,0.5,0.0,0.036,0.036,0.038,0.042,0.040,...,-0.006,-0.006,-0.006,-0.006,-0.004,-0.004,-0.004,-0.003,-0.003,-0.003
4,5.0,75.0,24.0,1.0,0.0,0.027,0.028,0.032,0.038,0.031,...,-0.004,-0.004,-0.004,-0.004,-0.002,-0.003,-0.002,-0.002,-0.002,-0.001
5,5.0,75.0,24.0,1.0,0.0,0.038,0.044,0.046,0.049,0.048,...,-0.005,-0.005,-0.005,-0.005,-0.003,-0.004,-0.003,-0.003,-0.003,-0.002
6,5.0,75.0,20.0,5.0,0.0,0.042,0.044,0.045,0.050,0.048,...,-0.008,-0.008,-0.008,-0.008,-0.006,-0.007,-0.006,-0.006,-0.006,-0.006
7,5.0,75.0,20.0,5.0,0.0,0.046,0.051,0.055,0.055,0.052,...,-0.007,-0.007,-0.007,-0.007,-0.005,-0.006,-0.005,-0.005,-0.005,-0.004
8,5.0,75.0,25.0,0.0,10.0,0.144,0.134,0.148,0.159,0.152,...,-0.005,-0.005,-0.005,-0.005,-0.004,-0.004,-0.003,-0.003,-0.003,-0.003
9,5.0,75.0,25.0,0.0,10.0,0.111,0.101,0.116,0.121,0.116,...,-0.009,-0.008,-0.009,-0.009,-0.008,-0.009,-0.007,-0.007,-0.007,-0.007
10,5.0,75.0,24.5,0.5,10.0,0.114,0.126,0.128,0.136,0.131,...,-0.008,-0.007,-0.008,-0.008,-0.006,-0.007,-0.006,-0.006,-0.006,-0.006
11,5.0,75.0,24.5,0.5,10.0,0.126,0.128,0.137,0.148,0.147,...,-0.007,-0.006,-0.007,-0.007,-0.005,-0.006,-0.005,-0.005,-0.005,-0.004
12,5.0,75.0,24.0,1.0,10.0,0.128,0.131,0.140,0.148,0.137,...,-0.009,-0.009,-0.009,-0.009,-0.008,-0.009,-0.007,-0.007,-0.007,-0.007
13,5.0,75.0,24.0,1.0,10.0,0.121,0.121,0.134,0.138,0.135,...,-0.008,-0.008,-0.008,-0.008,-0.006,-0.008,-0.006,-0.006,-0.006,-0.006
14,5.0,75.0,20.0,5.0,10.0,0.096,0.091,0.094,0.103,0.101,...,-0.009,-0.009,-0.009,-0.009,-0.007,-0.008,-0.007,-0.007,-0.007,-0.006
15,5.0,75.0,20.0,5.0,10.0,0.100,0.101,0.107,0.119,0.103,...,-0.008,-0.008,-0.008,-0.008,-0.006,-0.007,-0.006,-0.006,-0.006,-0.005
16,5.0,75.0,25.0,0.0,20.0,0.195,0.202,0.218,0.220,0.208,...,-0.007,-0.006,-0.007,-0.007,-0.005,-0.006,-0.005,-0.005,-0.005,-0.005
17,5.0,75.0,25.0,0.0,20.0,0.204,0.197,0.217,0.232,0.219,...,-0.008,-0.007,-0.008,-0.007,-0.006,-0.006,-0.005,-0.005,-0.005,-0.004
18,5.0,75.0,24.5,0.5,20.0,0.156,0.155,0.165,0.172,0.169,...,-0.008,-0.008,-0.008,-0.008,-0.006,-0.007,-0.005,-0.005,-0.005,-0.004
19,5.0,75.0,24.5,0.5,20.0,0.155,0.146,0.162,0.172,0.165,...,-0.010,-0.009,-0.009,-0.009,-0.008,-0.009,-0.007,-0.007,-0.007,-0.007
20,5.0,75.0,24.0,1.0,20.0,0.189,0.191,0.193,0.202,0.209,...,-0.010,-0.009,-0.010,-0.009,-0.008,-0.009,-0.007,-0.007,-0.007,-0.007
21,5.0,75.0,24.0,1.0,20.0,0.192,0.195,0.199,0.222,0.212,...,-0.009,-0.009,-0.009,-0.009,-0.007,-0.009,-0.007,-0.007,-0.007,-0.006
22,5.0,75.0,20.0,5.0,20.0,0.155,0.160,0.159,0.180,0.167,...,-0.009,-0.009,-0.010,-0.009,-0.008,-0.009,-0.007,-0.007,-0.007,-0.006
23,5.0,75.0,20.0,5.0,20.0,0.175,0.182,0.186,0.200,0.197,...,-0.007,-0.007,-0.007,-0.006,-0.005,-0.006,-0.004,-0.004,-0.004,-0.003