In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.colors as colors
import numpy as np
from scipy import interpolate, stats

In [2]:
import ProcessOT2DOE as process
import CreateSamples

C:\Users\Edwin\.opentrons\deck_calibration.json not found. Loading defaults
C:\Users\Edwin\.opentrons\robot_settings.json not found. Loading defaults

Loading json containers...
Json container file load complete, listing database
Found 0 containers to add. Starting migration...
Database migration complete!

# Step 1: Load Sample Information
* Will be in the form of a dataframe. This dataframe should be standardized in the original documentation.
* Either load locally or pull from the google drive.

In [10]:
sample_info = pd.read_csv(r"C:\Users\Edwin\Downloads\Experiment Synthesis Info")
sample_info

,UID,dppc wtf,dspepeg200 wtf,pfh wtf,ethanol wtf,water wtf,Well,Labware,Slot
0,A1_2021-03-03,0.0001,0.000035,0.000,0.157895,0.841970,A1,Falcon 48 Well Plate 1500 ÂµL,2
1,A2_2021-03-03,0.0001,0.000035,0.000,0.210526,0.789339,A2,Falcon 48 Well Plate 1500 ÂµL,2
2,A3_2021-03-03,0.0001,0.000035,0.000,0.263158,0.736707,A3,Falcon 48 Well Plate 1500 ÂµL,2
3,A4_2021-03-03,0.0001,0.000035,0.000,0.315789,0.684076,A4,Falcon 48 Well Plate 1500 ÂµL,2
4,A5_2021-03-03,0.0001,0.000035,0.000,0.368421,0.631444,A5,Falcon 48 Well Plate 1500 ÂµL,2
...,...,...,...,...,...,...,...,...,...
232,F1_2021-03-03,0.0001,0.000035,0.001,0.736842,0.262023,F1,Falcon 48 Well Plate 1500 ÂµL,9
233,F2_2021-03-03,0.0001,0.000035,0.001,0.789474,0.209391,F2,Falcon 48 Well Plate 1500 ÂµL,9
234,F3_2021-03-03,0.0001,0.000035,0.001,0.842105,0.156760,F3,Falcon 48 Well Plate 1500 ÂµL,9
235,F4_2021-03-03,0.0001,0.000035,0.001,0.894737,0.104128,F4,Falcon 48 Well Plate 1500 ÂµL,9
236,F5_2021-03-03,0.0001,0.000035,0.001,0.947368,0.051497,F5,Falcon 48 Well Plate 1500 ÂµL,9

# Step 2: Load UV-Vis Date
* ***If loading from plate reader***: Once the plate has been read, allow for exporting to an excel sheet and reformat for easy upload and merging.
    * The plate reader should automatically ask you if you would like to export to excel. When running multiple plates you can just keep selecting export and it will automatically add the new run as an additional sheet to the originally generated excel sheet. 
    * To format for easy loading:
        1. Create a new sheet in the same exported excel file and name it something simple (i.e. sheet1). 
        2. Copy the data from the sheet and add it to the newly created sheet. **NOTE**: Make sure to paste in the data as "only values". 
        3. Repeat for every single exported sheet (i.e. every plate)
* ***If loading from single cuvette reader***: 

* issue when over scanned on accident

In [11]:
def merge_wavelength_dfs(df_list):
    merge_list = []
    for i, df in enumerate(df_list):
        if i == 0:
            df = df
        else: 
            df = df.drop(['Wavelength'])
        print(len(df))
        merge_list.append(df)
    return pd.concat(merge_list)

In [28]:
path = r"C:\Users\Edwin\Downloads\02_26_21_OuzoScan (1).xlsx"
plate_names = ['Sheet1','Sheet2','Sheet3','Sheet4','Sheet5']
plate_dfs = process.extract_plates(path, plate_names) # can edit/remove wells accidently measured etc, but really should be done at excel level
merged_df = process.merge_wavelength_dfs(plate_dfs) # a check
merged_df = merged_df[:238] # since should be length n of sample info + 1 (wavelength)
merged_df.loc['Wavelength']

0     200.0
1     250.0
2     300.0
3     350.0
4     400.0
5     450.0
6     500.0
7     550.0
8     600.0
9     650.0
10    700.0
11    750.0
12    800.0
13    850.0
14    900.0
Name: Wavelength, dtype: float64

# Step 2: Select/Locate Blank 
* ***If loading from plate reader***: Once the plate has been read, allow for exporting to an excel sheet and reformat for easy upload and merging.
    * The plate reader should automatically ask you if you would like to export to excel. When running multiple plates you can just keep selecting export and it will automatically add the new run as an additional sheet to the originally generated excel sheet. 
    * To format for easy loading:
        1. Create a new sheet in the same exported excel file and name it something simple (i.e. sheet1). 
        2. Copy the data from the sheet and add it to the newly created sheet. **NOTE**: Make sure to paste in the data as "only values". 
        3. Repeat for every single exported sheet (i.e. every plate)
* ***If loading from single cuvette reader***:

In [29]:
def add_abs_to_sample_info(sample_info_df, abs_df):
    
    wavelengths = list(abs_df.loc['Wavelength'])
    wavelengths_names = [str(wavelength)+'nm' for wavelength in wavelengths]
    abs_df.columns = wavelengths_names
    abs_df.drop(['Wavelength'], inplace=True)

    
    
    sample_info_df.reset_index(drop=True, inplace=True)
    abs_df.reset_index(drop=True, inplace=True)
    combined_df = pd.concat([sample_info_df, abs_df], axis = 1)
    return combined_df

In [40]:
abs_df = merged_df.copy()
wavelengths = list(abs_df.loc['Wavelength'])
wavelengths_names = [str(wavelength)+'nm' for wavelength in wavelengths]
abs_df.columns = wavelengths_names
abs_df.drop(['Wavelength'], inplace=True)
abs_df

,200.0nm,250.0nm,300.0nm,350.0nm,400.0nm,450.0nm,500.0nm,550.0nm,600.0nm,650.0nm,700.0nm,750.0nm,800.0nm,850.0nm,900.0nm
A1,3.501,3.764,0.778,0.322,0.052,0.045,0.042,0.042,0.042,0.041,0.041,0.049,0.046,0.053,0.065
A2,3.490,3.770,0.755,0.315,0.054,0.044,0.040,0.040,0.040,0.038,0.038,0.045,0.043,0.049,0.063
A3,3.477,3.747,0.681,0.283,0.058,0.048,0.043,0.042,0.042,0.039,0.039,0.045,0.043,0.049,0.064
A4,3.473,3.741,0.659,0.273,0.060,0.049,0.045,0.043,0.042,0.039,0.038,0.045,0.043,0.048,0.065
A5,3.474,3.751,0.675,0.279,0.061,0.051,0.045,0.046,0.044,0.040,0.039,0.045,0.045,0.051,0.069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
F1,3.491,3.761,0.729,0.297,0.058,0.047,0.043,0.043,0.043,0.042,0.041,0.046,0.045,0.047,0.060
F2,3.474,3.744,0.677,0.271,0.052,0.045,0.041,0.040,0.039,0.037,0.037,0.041,0.041,0.043,0.061
F3,3.474,3.747,0.704,0.279,0.052,0.044,0.042,0.042,0.042,0.040,0.040,0.043,0.042,0.044,0.061
F4,3.479,3.760,0.736,0.294,0.052,0.042,0.039,0.039,0.039,0.037,0.036,0.039,0.038,0.039,0.055
F5,3.478,3.755,0.736,0.291,0.053,0.044,0.041,0.041,0.040,0.038,0.037,0.039,0.039,0.039,0.052

In [16]:
# baseline and combine
# baseline_series = merged_df.iloc[-1]
# merged_baselined_df = baseline_correction(merged_df, baseline_series)
combined_df = add_abs_to_sample_info(sample_info, merged_df)
combined_df

,UID,dppc wtf,dspepeg200 wtf,pfh wtf,ethanol wtf,water wtf,Well,Labware,Slot,200.0nm,...,450.0nm,500.0nm,550.0nm,600.0nm,650.0nm,700.0nm,750.0nm,800.0nm,850.0nm,900.0nm
0,A1_2021-03-03,0.0001,0.000035,0.000,0.157895,0.841970,A1,Falcon 48 Well Plate 1500 ÂµL,2.0,200.000,...,450.000,500.000,550.000,600.000,650.000,700.000,750.000,800.000,850.000,900.000
1,A2_2021-03-03,0.0001,0.000035,0.000,0.210526,0.789339,A2,Falcon 48 Well Plate 1500 ÂµL,2.0,3.501,...,0.045,0.042,0.042,0.042,0.041,0.041,0.049,0.046,0.053,0.065
2,A3_2021-03-03,0.0001,0.000035,0.000,0.263158,0.736707,A3,Falcon 48 Well Plate 1500 ÂµL,2.0,3.490,...,0.044,0.040,0.040,0.040,0.038,0.038,0.045,0.043,0.049,0.063
3,A4_2021-03-03,0.0001,0.000035,0.000,0.315789,0.684076,A4,Falcon 48 Well Plate 1500 ÂµL,2.0,3.477,...,0.048,0.043,0.042,0.042,0.039,0.039,0.045,0.043,0.049,0.064
4,A5_2021-03-03,0.0001,0.000035,0.000,0.368421,0.631444,A5,Falcon 48 Well Plate 1500 ÂµL,2.0,3.473,...,0.049,0.045,0.043,0.042,0.039,0.038,0.045,0.043,0.048,0.065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,F2_2021-03-03,0.0001,0.000035,0.001,0.789474,0.209391,F2,Falcon 48 Well Plate 1500 ÂµL,9.0,3.491,...,0.047,0.043,0.043,0.043,0.042,0.041,0.046,0.045,0.047,0.060
234,F3_2021-03-03,0.0001,0.000035,0.001,0.842105,0.156760,F3,Falcon 48 Well Plate 1500 ÂµL,9.0,3.474,...,0.045,0.041,0.040,0.039,0.037,0.037,0.041,0.041,0.043,0.061
235,F4_2021-03-03,0.0001,0.000035,0.001,0.894737,0.104128,F4,Falcon 48 Well Plate 1500 ÂµL,9.0,3.474,...,0.044,0.042,0.042,0.042,0.040,0.040,0.043,0.042,0.044,0.061
236,F5_2021-03-03,0.0001,0.000035,0.001,0.947368,0.051497,F5,Falcon 48 Well Plate 1500 ÂµL,9.0,3.479,...,0.042,0.039,0.039,0.039,0.037,0.036,0.039,0.038,0.039,0.055
237,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.478,...,0.044,0.041,0.041,0.040,0.038,0.037,0.039,0.039,0.039,0.052

In [7]:
CreateSamples.team_drive_dict()
current_members = CreateSamples.file_and_folder_navi('1dXYmxuESNhgmVHntEf8hnZmjK0Br8b64')
CreateSamples.file_and_folder_navi('1CDnoLE32bG0BFhhvCl5JlRFO4I_ga-eJ')
plan_file_path = experiment_plan_path
synthesis_info_file_path = r"sample_info"
folder_to_place_id = '19v4-bQnGwFyxoRpQAggCjAC4tgGVH7Fd'

CreateSamples.upload_to_team_drive_folder(folder_to_place_id, plan_file_path, 'Experiment Plan Info')
CreateSamples.upload_to_team_drive_folder(folder_to_place_id, synthesis_info_file_path, 'Experiment Synthesis Info')

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=976386138783-rlb4mpjsuqi7gf8qn60elpsdt46a4srl.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code

Authentication successful.

NameError: name 'experiment_plan_path' is not defined

In [ ]:
test_open = pd.read_csv(r"C:\Users\Edwin\Desktop\11_18_2020\11_18_20_merged_info")
test_open

In [ ]:
# extract data by dict method of df calling series
wavelength = '400.0nm'
x_name = combined_df['Component 4 wtf'][0]
y_name = combined_df['Component 3 wtf'][0]
x = [float(i) for i in combined_df['Component 4 wtf'][1:].tolist()][:-1] #ethanol, 
y = [float(i) for i in combined_df['Component 3 wtf'][1:].tolist()][:-1] # pfh
z = [float(i) for i in combined_df[wavelength][1:].tolist()][:-1]
combined_restricted_xyz = [x,y,z]
modi = remove_visual_outliers(x,y,z,2) # this should only be used to find the new vmin and vmax but not to exclude